mini_fiction/views/auth.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from datetime import datetime

from flask import Blueprint, current_app, request, render_template, redirect, url_for, flash
from flask_babel import gettext
from flask_login import login_user, logout_user, current_user
from pony.orm import db_session

from mini_fiction.models import Author
from mini_fiction.captcha import CaptchaError
from mini_fiction.validation import ValidationError
from mini_fiction.forms.login import LoginForm
from mini_fiction.forms.register import AuthorRegistrationForm, AuthorPasswordResetForm, AuthorNewPasswordForm
from mini_fiction.utils.misc import check_own_url


bp = Blueprint('auth', __name__)


@bp.route('/login/', methods=('GET', 'POST'))
@db_session
def login():
    page_title = gettext('Authorization')

    captcha = None
    captcha_error = None

    next_url = check_own_url(
        request.form.get("next") or request.args.get("next") or request.referrer
    ) or url_for("index.index")

    form = LoginForm()
    if form.validate_on_submit():
        data = dict(form.data)
        if current_app.captcha:
            data = current_app.captcha.copy_fields(data, request.form)

        try:
            user = Author.bl.authenticate_by_username(data, request.remote_addr)
            if not login_user(user, remember=True):
                raise ValidationError({'username': [gettext('Cannot login')]})
        except ValidationError as exc:
            form.set_errors(exc.errors)
        except CaptchaError:
            captcha_error = 'Вы не доказали, что вы не робот'
            if not captcha:
                captcha = current_app.captcha.generate()
        else:
            user.last_login = datetime.utcnow()
            user.last_visit = user.last_login
            return redirect(next_url)

    if not captcha and current_app.captcha and Author.bl.need_captcha_for_auth(request.remote_addr):
        captcha = current_app.captcha.generate()

    return render_template(
        'registration/login.html',
        form=form,
        page_title=page_title,
        captcha=captcha,
        captcha_error=captcha_error,
        next_url=next_url,
    )


@bp.route('/register/', methods=('GET', 'POST'))
@db_session
def registration():
    if not current_app.config['REGISTRATION_OPEN']:
        return render_template('registration/registration_closed.html', page_title=gettext('Registration is closed'))

    page_title = gettext('Registration in library')

    captcha = None
    captcha_error = None
    if current_app.captcha:
        captcha = current_app.captcha.generate()

    form = AuthorRegistrationForm()
    if form.validate_on_submit():
        data = dict(form.data)
        if current_app.captcha:
            data = current_app.captcha.copy_fields(data, request.form)
        try:
            Author.bl.register(data)
        except CaptchaError:
            captcha_error = 'Вы не доказали, что вы не робот'
        except ValidationError as exc:
            form.set_errors(exc.errors)
        else:
            if current_app.config['AUTH_LOG']:
                current_app.logger.info('%s requested registration (ID: N/A, IP: %s)', data.get('username'), request.remote_addr)
            return redirect(url_for('auth.registration_complete'))

    return render_template(
        'registration/registration_form.html',
        form=form,
        captcha=captcha,
        captcha_error=captcha_error,
        page_title=page_title,
        username_help=current_app.config['USERNAME_HELP'],
    )


@bp.route('/register/complete/', methods=('GET',))
@db_session
def registration_complete():
    return render_template('registration/registration_complete.html', robots_noindex=True)


@bp.route('/activate/<activation_key>/', methods=('GET',))
@db_session
def registration_activate(activation_key):
    user = Author.bl.activate(activation_key)
    if user:
        if current_app.config['AUTH_LOG']:
            current_app.logger.info('%s registered and activated (ID: %s, IP: %s)', user.username, user.id, request.remote_addr)
        if current_app.config['REGISTRATION_AUTO_LOGIN']:
            login_user(user, remember=True)
        return render_template('registration/activation_complete.html', robots_noindex=True)
    else:
        return render_template('registration/activate.html', robots_noindex=True)


@bp.route('/password/reset/', methods=('GET', 'POST'))
@db_session
def password_reset():
    page_title = 'Восстановление пароля: введите адрес e-mail'

    form = AuthorPasswordResetForm()
    if form.validate_on_submit():
        clean_email = form.email.data.lower().strip()
        users = Author.select(lambda x: x.email.lower() == clean_email)[:2]

        if len(users) == 1:
            users[0].bl.reset_password_by_email()
            return redirect(url_for('auth.password_reset_done'))

        if not users:
            form.set_errors({'email': ['Пользователь с таким e-mail не найден']})
        else:  # len(users) > 1
            form.set_errors({'email': [
                'Как-то получилось, что этот e-mail есть у нескольких пользователей. '
                'Обратитесь к администрации для разбирательств'
            ]})

    return render_template('registration/password_reset_form.html', form=form, page_title=page_title)


@bp.route('/password/reset/done/')
@db_session
def password_reset_done():
    page_title = 'Восстановление пароля: письмо отправлено'
    return render_template('registration/password_reset_done.html', page_title=page_title, robots_noindex=True)


@bp.route('/password/reset/<activation_key>/', methods=('GET', 'POST'))
@db_session
def password_reset_confirm(activation_key):
    page_title = 'Восстановление пароля: новый пароль'
    user = Author.bl.get_by_password_reset_key(activation_key)
    if not user:
        return render_template('registration/password_reset_confirm.html', validlink=False, page_title=page_title)

    form = AuthorNewPasswordForm()
    if form.validate_on_submit():
        if current_app.config['CHECK_PASSWORDS_SECURITY'] and not user.bl.is_password_good(form.new_password1.data):
            flash(gettext('Password is too bad, please change it'))
        else:
            user.bl.set_password(form.new_password1.data)
            if not user.bl.activate_password_reset_key(activation_key):
                raise RuntimeError('activate_password_reset_key returns False')
            return redirect(url_for('auth.password_reset_complete'))
    return render_template('registration/password_reset_confirm.html', validlink=True, form=form, page_title=page_title, robots_noindex=True)


@bp.route('/password/done/')
@db_session
def password_reset_complete():
    page_title = 'Восстановление пароля: пароль восстановлен'
    return render_template('registration/password_reset_complete.html', page_title=page_title, robots_noindex=True)


@bp.route('/changemail/<activation_key>/', methods=('GET',))
@db_session
def new_email_activate(activation_key):
    user = Author.bl.activate_changed_email(activation_key)
    if user:
        if current_app.config['REGISTRATION_AUTO_LOGIN']:
            login_user(user, remember=True)
        return render_template('registration/change_email_complete.html', robots_noindex=True)
    else:
        return render_template('registration/change_email_failed.html', robots_noindex=True)


@bp.route('/logout/', methods=('GET',))
@db_session
def logout():
    if current_app.config['AUTH_LOG'] and current_user.is_authenticated:
        current_app.logger.info('%s logged out (ID: %s, IP: %s)', current_user.username, current_user.id, request.remote_addr)
    logout_user()
    next_url = check_own_url(
        request.args.get("next") or request.referrer
    ) or url_for("index.index")
    return redirect(next_url)

mini_fiction/views/news.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from flask import Blueprint, current_app, render_template, abort, request, jsonify, redirect, url_for
from flask_babel import gettext
from flask_login import current_user, login_required
from markupsafe import Markup
from pony.orm import db_session, desc

from mini_fiction.models import NewsItem
from mini_fiction.forms.comment import CommentForm
from mini_fiction.utils.views import paginate_view
from mini_fiction.utils.misc import calc_maxdepth

bp = Blueprint('news', __name__)


@bp.route('/page/last/', defaults={'page': -1})
@bp.route('/', defaults={'page': 1})
@bp.route('/page/<int:page>/')
@db_session
def index(page):
    objects = NewsItem.select().sort_by(desc(NewsItem.id))

    return paginate_view(
        'news/index.html',
        objects,
        count=objects.count(),
        page_title=gettext('News'),
        objlistname='news',
        per_page=100,
    )


@bp.route('/<name>/', defaults={'comments_page': -1})
@bp.route('/<name>/comments/page/<int:comments_page>/')
@db_session
def show(name, comments_page):
    newsitem = NewsItem.get(name=name)
    if not newsitem:
        abort(404)

    if newsitem.is_template:
        template = current_app.jinja_env.from_string(newsitem.content)
        template.name = 'db/news/{}.html'.format(name)
        content = render_template(template, newsitem_name=newsitem.name, newsitem_title=newsitem.title)
    else:
        content = newsitem.content

    per_page = current_user.comments_per_page or current_app.config['COMMENTS_COUNT']['page']
    maxdepth = None if request.args.get('fulltree') == '1' else calc_maxdepth(current_user)

    comments_count, paged, comments_tree_list = newsitem.bl.paginate_comments(comments_page, per_page, maxdepth)
    paged.page_arg_name = 'comments_page'
    if not comments_tree_list and paged.number != 1:
        abort(404)

    comment_ids = [x[0].id for x in comments_tree_list]
    if current_user.is_authenticated:
        comment_votes_cache = newsitem.bl.select_comment_votes(current_user, comment_ids)
    else:
        comment_votes_cache = {i: 0 for i in comment_ids}

    data = {
        'page_title': newsitem.title,
        'newsitem': newsitem,
        'content': Markup(content),
        'comments_count': comments_count,
        'page_obj': paged,
        'comments_tree_list': comments_tree_list,
        'comment_form': CommentForm(),
        'comment_votes_cache': comment_votes_cache,
        'sub_comments': newsitem.bl.get_comments_subscription(current_user),
    }

    return render_template('news/show.html', **data)


@bp.route('/<name>/comments/subscribe/', methods=('POST',))
@db_session
@login_required
def comments_subscribe(name):
    newsitem = NewsItem.get(name=name)
    if not newsitem:
        abort(404)

    newsitem.bl.subscribe_to_comments(
        current_user,
        email=request.form.get('email') == '1',
        tracker=request.form.get('tracker') == '1',
    )

    if request.form.get('short') == '1':
        return jsonify(success=True)
    return redirect(url_for('newsitem.show', name=newsitem.name))

mini_fiction/templates/news/comment_delete.html
{% extends base %}
{% from 'macro.html' import comment_html with context %}
{% block content %}
<div class="row">
    <div class="span8">
    <h1>{{ page_title }}</h1>


    <div class="comment-item" id="{{ comment.local_id }}">
    {{ comment_html(comment, with_controls=False, with_vote=False) }}
    </div>
    {%- include 'includes/comment_delete_warning.html' with context -%}

    <form method="POST" enctype="multipart/form-data">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
          <div class="control-group">
            <div class="controls">
                <input type="submit" class="btn btn-danger" value="Удалить комментарий">
            </div>
        </div>
    </form>
    </div>
</div>
{% endblock %}

mini_fiction/templates/news/comment_delete_ajax.html
{% from 'macro.html' import comment_html with context %}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>{{ page_title }}</h3>
</div>
<div class="modal-body">
    <div class="comment-item" id="{{ comment.local_id }}">
        {{ comment_html(comment, with_controls=False, with_vote=False) }}
    </div>
    {%- include 'includes/comment_delete_warning.html' with context -%}
</div>
<div class="modal-footer">
    <form method="POST" action="{{ url_for('news_comment.delete', news_id=newsitem.id, local_id=comment.local_id) }}" style="margin: 0">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <button class="btn" data-dismiss="modal" aria-hidden="true">Отменить</button>
        <button type="submit" class="btn btn-danger ajax_comment_delete">Удалить комментарий</a>
    </form>
</div>

mini_fiction/templates/news/comment_restore.html
{% extends base %}
{% from 'macro.html' import comment_html with context %}
{% block content %}
<div class="row">
    <div class="span8">
    <h1>{{ page_title }}</h1>


    <div class="comment-item" id="{{ comment.local_id }}">
    {{ comment_html(comment, with_controls=False, with_vote=False) }}
    </div>

    <form method="POST" enctype="multipart/form-data">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
          <div class="control-group">
            <div class="controls">
                <input type="submit" class="btn btn-danger" value="Восстановить комментарий">
            </div>
        </div>
    </form>
    </div>
</div>
{% endblock %}

mini_fiction/templates/news/comment_restore_ajax.html
{% from 'macro.html' import comment_html with context %}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3>{{ page_title }}</h3>
</div>
<div class="modal-body">
    <div class="comment-item" id="{{ comment.local_id }}">
        {{ comment_html(comment, with_controls=False, with_vote=False) }}
    </div>
</div>
<div class="modal-footer">
    <form method="POST" action="{{ url_for('news_comment.restore', news_id=newsitem.id, local_id=comment.local_id) }}" style="margin: 0">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <button class="btn" data-dismiss="modal" aria-hidden="true">Отменить</button>
        <button type="submit" class="btn btn-danger ajax_comment_restore">Восстановить комментарий</a>
    </form>
</div>

mini_fiction/templates/news/comment_work.html
{% extends base %}
{% from 'macro.html' import comment_html with context %}
{% block content %}
<div class="row">
    <div class="span12">

    <h1>{{ page_title }}</h1>

    {% if edit -%}
        <div class="comment-item" id="{{ comment.local_id }}">
        {{ comment_html(comment, with_controls=False, with_vote=False) }}
        </div>
    {%- elif parent_comment -%}
        <div class="comment-item" id="{{ parent_comment.local_id }}">
        {{ comment_html(parent_comment, with_controls=False, with_vote=False) }}
        </div>
    {%- endif %}

    <form class="comment-form" method="POST" enctype="multipart/form-data" action="">
    {% from 'macro.html' import comment_form_content with context %}
    {{ comment_form_content(form, 'newsitem', newsitem.id, parent_comment.local_id if parent_comment else None, preview_html=preview_html, reqs=comment_reqs) }}
    </form>

    </div>
</div>
{% endblock %}

mini_fiction/templates/news/comments_pagination.html
{% if page_obj.num_pages != 1 -%}
    {% for page_id in page_obj.iter_pages() %}
        <a
            href="{{ url_for('news.show', name=newsitem.name, comments_page=page_id) }}"
            data-ajax-href="{{ url_for('news_comment.ajax', news_id=newsitem.id, page=page_id) }}"
            class="js-comment-pagination-btn btn{% if page_id == page_obj.number %} btn-primary{% endif %}">
            {{- page_id -}}
        </a>
    {% endfor %}
{%- endif %}

mini_fiction/templates/news/index.html
{% extends base %}
{% from 'macro.html' import paginator with context %}
{% block content %}
<div class="row">
    <div class="span8">
        <h2>{{ page_title }}</h2>

        <div class="news-list">
        {% for newsitem in news %}
        <div class="newsitem newsitem-listitem" id="newsitem_{{ newsitem.id }}">
            <a href="{{ url_for('news.show', name=newsitem.name) }}" class="newsitem-title-link">{{ newsitem.title }}</a>
            {% if current_user.is_staff -%}
                <div class="icon-group">
                    <a title="{{ _('Edit') }}"
                       aria-label="{{ _('Edit') }}"
                       role="button"
                       class="scon entity-edit"
                       href="{{ url_for('admin_news.update', pk=newsitem.id) }}"></a>
                </div>
            {%- endif %}
            <br/>
            <time datetime="{{ newsitem.date.strftime('%Y-%m-%dT%H:%M:%SZ') }}" class="newsitem-date">
                {{- newsitem.date|datetimeformat(DEFAULT_DATE_FORMAT) -}}, {{ ngettext("%(num)d comment", "%(num)d comments", newsitem.comments_count) }}
            </time>
        </div>
        {% endfor %}
        </div>

        {{ paginator(page_obj) }}
    </div>
</div>
{% endblock %}

mini_fiction/templates/news/show.html
{% extends base %}
{% block content %}
<div class="row">
    <div class="span12">
        <div class="newsitem newsitem-listitem" id="newsitem_{{ newsitem.id }}">
            <span class="newsitem-title-link">{{ newsitem.title }}</span>
            {% if current_user.is_staff -%}
                <div class="icon-group">
                    <a title="{{ _('Edit') }}"
                       aria-label="{{ _('Edit') }}"
                       role="button"
                       class="scon entity-edit"
                       href="{{ url_for('admin_news.update', pk=newsitem.id) }}"></a>
                </div>
            {%- endif %}
            <br/>
            <time datetime="{{ newsitem.date.strftime('%Y-%m-%dT%H:%M:%SZ') }}" class="newsitem-date">
                {{- newsitem.date|datetimeformat(DEFAULT_DATE_FORMAT) -}}
            </time>
            <div class="newsitem-content">{{ content }}</div>
        </div>

        <!-- Вывод комментариев: начало -->
        <div id="comments">
            <h3>Комментарии (<span id="comments-count">{{ comments_count }}</span>)</h3>
            {% if current_user.is_authenticated %}
                <form method="POST" action="{{ url_for('news.comments_subscribe', name=newsitem.name) }}" class="subscription-form js-subscription-form">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                    Получать новые:
                    <label><input type="checkbox" name="email" value="1"{% if sub_comments.email %} checked{% endif %} /> в почте</label>
                    <label><input type="checkbox" name="tracker" value="1"{% if sub_comments.tracker %} checked{% endif %} /> на сайте</label>
                    <button type="submit" class="btn btn-mini js-subscription-form-submit">Сохранить</button>
                </form>
            {% endif %}
            <div id="comments-tree" class="comments-tree">
                {% if comments_count > 0 %}
                    {%- include 'includes/comments_tree.html' -%}
                {% endif %}
            </div>

            <div id="comments-pagination" class="pagination center">
            {% if comments_count > 0 %}
                {%- include 'news/comments_pagination.html' -%}
            {% endif %}
            </div>
        </div>

        {% set comment_reqs = newsitem.bl.access_for_commenting_by(current_user) %}
        {% if comment_reqs %}
            <a href="{{ url_for('news_comment.add', news_id=newsitem.id) }}" id="comment-add-link" class="comment-add-link">Добавить новый комментарий</a>

            <form id="comment-form" class="comment-form" method="POST" enctype="multipart/form-data" action="{{- url_for('news_comment.add', news_id=newsitem.id) -}}">
            {% from 'macro.html' import comment_form_content with context %}
            {{ comment_form_content(comment_form, reqs=comment_reqs) }}
            </form>
        {% elif current_user.is_authenticated %}
        <h3 id="banned">К сожалению, Вы не можете добавлять комментарии</h3>
        {% else %}
        <a href="{{ url_for('auth.login', next=url_for('news.show', name=newsitem.name)) }}">Авторизуйтесь</a> для отправки комментария.
        {% endif %}
        <!-- Вывод комментариев: конец -->
    </div>
</div>
{% endblock %}