mini_fiction/forms/comment.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from flask import current_app
from markupsafe import Markup
from wtforms import TextAreaField, ValidationError

from mini_fiction.forms.form import Form


class CommentForm(Form):
    attrs_dict = {'class': 'span4 js-form-saving', 'data-bazooka': 'RichEditor'}

    text = TextAreaField(
        '',
        render_kw=dict(attrs_dict, data_formsaving='comment', data_formgroup='comment', maxlength=8192, placeholder='Текст нового комментария', id='id_text', rows=10, cols=40)
    )

    def validate_text(self, field):
        # TODO: а как вот это на cerberus перенести?
        if len(Markup(field.data).striptags()) < current_app.config['COMMENT_MIN_LENGTH']:
            raise ValidationError('Сообщение слишком короткое!')

mini_fiction/views/feeds.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from datetime import datetime, timedelta

import pytz
from flask import Blueprint, Response, current_app, url_for, request, abort
from flask_babel import gettext, ngettext
from feedgen.feed import FeedGenerator
from markupsafe import Markup
from pony.orm import select, db_session, desc

from mini_fiction.models import Story, Chapter, Author
from mini_fiction.utils.misc import sitename


bp = Blueprint('feeds', __name__)


def _add_story_entry(feed, story, order='append'):
    entry = feed.add_entry(order=order)
    entry.id(url_for('story.view', pk=story.id, _external=True))
    entry.link(href=url_for('story.view', pk=story.id, _external=True))
    entry.title(story.title)
    entry.content(Markup(story.summary).striptags())
    entry.author([
        {'name': author.username, 'uri': url_for('author.info', user_id=author.id, _external=True)}
        for author in story.bl.get_authors()
    ])
    entry.published(pytz.UTC.fromutc(story.first_published_at or story.date))
    entry.updated(pytz.UTC.fromutc(
        max(story.first_published_at or story.date, story.updated)
    ))

    return entry


def _add_stories_to_feed(feed, stories):
    last_update = datetime(1970, 1, 1, 0)

    for story in stories:
        _add_story_entry(feed, story)
        last_update = max(
            last_update,
            story.first_published_at or story.date,
            story.updated,
        )

    return last_update


@bp.route('/stories/', endpoint='stories')
@db_session
def feed_stories():
    feed = FeedGenerator()
    feed.title('Новые рассказы — {}'.format(sitename()))
    feed.subtitle('Новые фанфики')
    feed.id(request.url)
    feed.link(href=request.url, rel='self')

    count = current_app.config['RSS'].get('stories', 20)
    stories = Story.select_published().sort_by(desc(Story.first_published_at), desc(Story.id))[:count]
    last_update = _add_stories_to_feed(feed, stories)

    feed.updated(pytz.UTC.fromutc(last_update))
    return Response(feed.atom_str(pretty=True), mimetype='application/atom+xml')


@bp.route('/stories/top/', endpoint='top')
@db_session
def feed_stories_top():
    period = request.args.get('period', 0)
    try:
        period = int(period)
    except ValueError:
        period = 0

    if period == 7:
        title = gettext('Top stories for the week')
    elif period == 30:
        title = gettext('Top stories for the month')
    elif period == 365:
        title = gettext('Top stories for the year')
    elif period == 0:
        title = gettext('Top stories for all time')
    else:
        title = ngettext('Top stories in %(num)d day', 'Top stories in %(num)d days', period)

    feed = FeedGenerator()
    feed.title('{} — {}'.format(title, sitename()))
    feed.subtitle('Топ рассказов')
    feed.id(request.url)
    feed.link(href=request.url, rel='self')

    count = current_app.config['RSS'].get('stories', 20)
    stories = Story.bl.select_top(period)[:count]
    last_update = _add_stories_to_feed(feed, stories)

    feed.updated(pytz.UTC.fromutc(last_update))
    return Response(feed.atom_str(pretty=True), mimetype='application/atom+xml')


@bp.route('/accounts/<int:user_id>/', endpoint='accounts')
@db_session
def feed_accounts(user_id):
    author = Author.get(id=user_id)
    if not author:
        abort(404)

    feed = FeedGenerator()
    feed.title('Новые рассказы автора {} — {}'.format(author.username, sitename()))
    feed.subtitle('Новые фанфики')
    feed.id(request.url)
    feed.link(href=request.url, rel='self')

    count = current_app.config['RSS'].get('accounts', 10)
    stories = Story.bl.select_by_author(author).sort_by(desc(Story.first_published_at), desc(Story.id))[:count]
    last_update = _add_stories_to_feed(feed, stories)

    feed.updated(pytz.UTC.fromutc(last_update))
    return Response(feed.atom_str(pretty=True), mimetype='application/atom+xml')


@bp.route('/chapters/', endpoint='chapters')
@db_session
def feed_chapters():
    feed = FeedGenerator()
    feed.title('Обновления глав — {}'.format(sitename()))
    feed.subtitle('Новые главы рассказов')
    feed.id(request.url)
    feed.link(href=request.url, rel='self')
    last_update = datetime(1970, 1, 1, 0)

    chapters = select(c for c in Chapter if not c.draft and c.story_published)
    chapters = chapters.sort_by(desc(Chapter.first_published_at), desc(Chapter.order))
    count = current_app.config['RSS'].get('chapters', 20)
    chapters = chapters.prefetch(Chapter.story)[:count]

    for chapter in chapters:
        story = chapter.story
        data = chapter.text_preview
        chapter_url = url_for('chapter.view', story_id=story.id, chapter_order=chapter.order, _external=True)

        entry = feed.add_entry(order='append')
        entry.id(chapter_url)
        entry.link(href=chapter_url)
        entry.title('{} : {}'.format(chapter.autotitle, story.title))
        entry.content(data)
        entry.author([
            {'name': author.username, 'uri': url_for('author.info', user_id=author.id, _external=True)}
            for author in story.bl.get_authors()
        ])
        entry.published(pytz.UTC.fromutc(chapter.date))
        entry.updated(pytz.UTC.fromutc(chapter.updated))
        last_update = max(last_update, chapter.updated)

    feed.updated(pytz.UTC.fromutc(last_update))
    return Response(feed.atom_str(pretty=True), mimetype='application/atom+xml')


@bp.route('/story/<int:story_id>/', endpoint='story')
@db_session
def feed_story(story_id):
    story = Story.select_published().filter(lambda x: x.id == story_id).prefetch(Story.chapters).first()
    if not story:
        abort(404)

    feed = FeedGenerator()
    feed.title(story.title)
    feed.id(request.url)
    feed.link(href=request.url, rel='self')
    last_update = datetime(1970, 1, 1, 0)

    chapters = [c for c in story.chapters if not c.draft]
    for c in chapters:
        assert c.first_published_at is not None, 'database is inconsistent: story {} has non-draft and non-published chapter {}'.format(story.id, c.order)
    chapters.sort(key=lambda x: (x.first_published_at, x.order), reverse=True)

    for chapter in chapters:
        data = chapter.text_preview
        chapter_url = url_for('chapter.view', story_id=story.id, chapter_order=chapter.order, _external=True)

        entry = feed.add_entry(order='append')
        entry.id(chapter_url)
        entry.link(href=chapter_url)
        entry.title(chapter.autotitle)
        entry.content(data)
        entry.published(pytz.UTC.fromutc(chapter.date))
        entry.updated(pytz.UTC.fromutc(chapter.updated))
        last_update = max(last_update, chapter.updated)

    feed.updated(pytz.UTC.fromutc(last_update))
    return Response(feed.atom_str(pretty=True), mimetype='application/atom+xml')

mini_fiction/views/stream.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from pony import orm
from pony.orm import db_session
from flask import Blueprint, current_app, render_template, abort, request
from flask_babel import gettext
from flask_login import current_user

from mini_fiction.bl.migration import enrich_stories
from mini_fiction.models import Story, Chapter, StoryContributor, StoryComment, StoryLocalComment, NewsComment, StoryTag, Tag
from mini_fiction.utils.views import cached_lists
from mini_fiction.utils.misc import Paginator, IndexPaginator


bp = Blueprint('stream', __name__)


@bp.route('/stories/page/last/', defaults={'page': -1})
@bp.route('/stories/', defaults={'page': 1})
@bp.route('/stories/page/<int:page>/')
@db_session
def stories(page):
    objects = Story.select_published().filter(lambda x: not x.pinned)
    objects = objects.sort_by(orm.desc(Story.first_published_at), orm.desc(Story.id))
    objects = objects.prefetch(
        Story.characters, Story.contributors, StoryContributor.user,
        Story.tags, StoryTag.tag, Tag.category,
    )

    page_obj = IndexPaginator(
        page,
        total=objects.count(),
        per_page=current_app.config['STORIES_COUNT']['stream'],
    )
    objects = page_obj.slice(objects)

    if page == 1:
        pinned_stories = list(
            Story.select_published().filter(lambda x: x.pinned).sort_by(orm.desc(Story.first_published_at))
        )
        objects = pinned_stories + objects

    if not objects and page != 1:
        abort(404)

    enrich_stories(objects)

    return render_template(
        'stream/stories.html',
        page_title='Лента добавлений',
        stories=objects,
        page_obj=page_obj,
        robots_noindex=True,
        **cached_lists([x.id for x in objects], chapter_view_dates=current_user.detail_view)
    )


@bp.route('/chapters/page/last/', defaults={'page': -1})
@bp.route('/chapters/', defaults={'page': 1})
@bp.route('/chapters/page/<int:page>/')
@db_session
def chapters(page):
    objects = orm.select(c for c in Chapter if not c.draft and c.story_published and c.order != 1)
    objects = objects.prefetch(Chapter.text, Chapter.story, Story.contributors, StoryContributor.user)
    objects = objects.sort_by(orm.desc(Chapter.first_published_at), orm.desc(Chapter.order))

    page_obj = Paginator(page, objects.count(), per_page=current_app.config['CHAPTERS_COUNT']['stream'])
    objects = page_obj.slice_or_404(objects)

    return render_template(
        'stream/chapters.html',
        page_title=gettext('Updates feed'),
        chapters=objects,
        page_obj=page_obj,
        robots_noindex=True,
        **cached_lists([x.story.id for x in objects])
    )


@bp.route('/comments/page/last/', defaults={'page': -1})
@bp.route('/comments/', defaults={'page': 1})
@bp.route('/comments/page/<int:page>/')
@db_session
def comments(page):
    objects = StoryComment.select(lambda x: x.story_published)
    filter_deleted = current_user.is_staff and request.args.get('deleted') == '1'
    if filter_deleted:
        objects = objects.filter(lambda x: x.deleted).sort_by(orm.desc(StoryComment.last_deleted_at))
    else:
        objects = objects.filter(lambda x: not x.deleted).sort_by(orm.desc(StoryComment.id))

    view_args = dict(request.view_args)
    if filter_deleted:
        view_args['deleted'] = '1'
    page_obj = Paginator(
        page,
        objects.count(),
        per_page=current_app.config['COMMENTS_COUNT']['stream'],
        view_args=view_args,
    )
    objects = [('story', x) for x in page_obj.slice_or_404(objects)]

    comment_votes_cache = Story.bl.select_comment_votes(
        current_user,
        [x[1].id for x in objects]
    ) if current_user.is_authenticated else {}

    return render_template(
        'stream/comments.html',
        page_title=gettext('Comments feed'),
        tab='story',
        comments=objects,
        filter_deleted=filter_deleted,
        with_target_link=True,
        comment_votes_cache=comment_votes_cache,
        page_obj=page_obj,
        robots_noindex=True,
        **cached_lists([x[1].story.id for x in objects])
    )


@bp.route('/localcomments/page/last/', defaults={'page': -1})
@bp.route('/localcomments/', defaults={'page': 1})
@bp.route('/localcomments/page/<int:page>/')
@db_session
def storylocalcomments(page):
    if not current_user.is_staff:
        abort(403)

    objects = StoryLocalComment.select()
    filter_deleted = current_user.is_staff and request.args.get('deleted') == '1'
    if filter_deleted:
        objects = objects.filter(lambda x: x.deleted).sort_by(orm.desc(StoryLocalComment.last_deleted_at))
    else:
        objects = objects.filter(lambda x: not x.deleted).sort_by(orm.desc(StoryLocalComment.id))

    view_args = dict(request.view_args)
    if filter_deleted:
        view_args['deleted'] = '1'
    page_obj = Paginator(
        page,
        objects.count(),
        per_page=current_app.config['COMMENTS_COUNT']['stream'],
        view_args=view_args,
    )
    objects = [('local', x) for x in page_obj.slice_or_404(objects)]

    comment_votes_cache = {}  # FIXME: здесь пересечение айдишников с айдшниками комментов к рассказам

    return render_template(
        'stream/comments.html',
        page_title=gettext('Comments feed'),
        tab='local',
        comments=objects,
        filter_deleted=filter_deleted,
        with_target_link=True,
        comment_votes_cache=comment_votes_cache,
        page_obj=page_obj,
        robots_noindex=True,
    )


@bp.route('/newscomments/page/last/', defaults={'page': -1})
@bp.route('/newscomments/', defaults={'page': 1})
@bp.route('/newscomments/page/<int:page>/')
@db_session
def newscomments(page):
    objects = NewsComment.select()
    filter_deleted = current_user.is_staff and request.args.get('deleted') == '1'
    if filter_deleted:
        objects = objects.filter(lambda x: x.deleted).sort_by(orm.desc(NewsComment.last_deleted_at))
    else:
        objects = objects.filter(lambda x: not x.deleted).sort_by(orm.desc(NewsComment.id))

    view_args = dict(request.view_args)
    if filter_deleted:
        view_args['deleted'] = '1'
    page_obj = Paginator(
        page,
        objects.count(),
        per_page=current_app.config['COMMENTS_COUNT']['stream'],
        view_args=view_args,
    )
    objects = [('news', x) for x in page_obj.slice_or_404(objects)]

    comment_votes_cache = {}  # FIXME: здесь пересечение айдишников с айдшниками комментов к рассказам

    return render_template(
        'stream/comments.html',
        page_title=gettext('Comments feed'),
        tab='news',
        comments=objects,
        filter_deleted=filter_deleted,
        with_target_link=True,
        comment_votes_cache=comment_votes_cache,
        page_obj=page_obj,
        robots_noindex=True,
    )

mini_fiction/templates/stream/chapters.html
{% extends base %}
{% from 'macro.html' import atom_feed with context %}
{% from 'macro.html' import paginator with context %}

{% block feeds %}
    {{ atom_feed(url_for('feeds.chapters'), _('Updates feed'), False) }}
{% endblock %}

{% block feeds_footer %}
    <li>{{ atom_feed(url_for('feeds.chapters'), _('Updates feed'), True) }}</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="span8">
        <h1>{{ page_title }}</h1>
        <div id="chapters-list">
            {% include "includes/chapters_excerpts.html" %}
        </div>
        {% if chapters %}{{ paginator(page_obj) }}{% endif %}
    </div>
</div>
{% endblock %}

mini_fiction/templates/stream/comments.html
{% extends base %}
{% from 'macro.html' import paginator with context %}
{% block content %}
<div class="row">
    <div class="span8">
        <h1>{{ page_title }}</h1>

        <div>
            {% if tab != 'story' %}<a href="{{ url_for('stream.comments') }}">{% endif -%}
                К рассказам
            {%- if tab != 'story' %}</a>{% endif %}
            &nbsp; &nbsp;
            {% if tab != 'news' %}<a href="{{ url_for('stream.newscomments') }}">{% endif -%}
                К новостям
            {%- if tab != 'news' %}</a>{% endif %}
            {% if current_user.is_staff %}
            &nbsp; &nbsp;
            {% if tab != 'local' %}<a href="{{ url_for('stream.storylocalcomments') }}">{% endif -%}
                В редакторской
            {%- if tab != 'local' %}</a>{% endif %}
            {% endif %}
        </div>
        <br/>

        {%- if current_user.is_staff %}<div>
            {% if filter_deleted %}<a href="{{ modified_url(view_args|default(None), page=1, deleted=None) }}">{% endif -%}
                Неудалённые
            {%- if filter_deleted %}</a>{% endif %}
            &nbsp; &nbsp;
            {% if not filter_deleted %}<a href="{{ modified_url(view_args|default(None), page=1, deleted='1') }}">{% endif -%}
                Удалённые
            {%- if not filter_deleted %}</a>{% endif %}
        </div><br/>{% endif -%}

        <div id="comments-list">
            {% include "includes/comments_list.html" %}
        </div>
        {% if comments %}{{ paginator(page_obj) }}{% endif %}
    </div>
</div>
{% endblock %}

mini_fiction/templates/stream/stories.html
{% extends "stories_list_common.html" %}
{% set buttons='common' %}

{% from 'macro.html' import atom_feed with context %}
{% from 'macro.html' import paginator with context %}

{% block feeds %}
    {{ atom_feed(url_for('feeds.stories'), _('New stories'), False) }}
{% endblock %}

{% block feeds_footer %}
    <li>{{ atom_feed(url_for('feeds.stories'), _('New stories'), True) }}</li>
{% endblock %}

{% block after_list %}
    {% if stories %}{{ paginator(page_obj) }}{% endif %}
{% endblock %}

mini_fiction/templates/stream/stories_top.html
{% extends "stories_list_common.html" %}
{% set buttons='common' %}

{% from 'macro.html' import atom_feed with context %}
{% from 'macro.html' import paginator with context %}

{% block feeds %}
    {{ atom_feed(url_for('feeds.top', period=period or None), 'Топ рассказов', False) }}
{% endblock %}

{% block feeds_footer %}
    <li>{{ atom_feed(url_for('feeds.top', period=period or None), 'Топ рассказов', True) }}</li>
{% endblock %}

{% block before_list %}
<div>
    {% if period != 7 %}<a href="{{ modified_url(period='7', page=1) }}">{% endif -%}
        За неделю
    {%- if period != 7 %}</a>{% endif %}
    &nbsp; &nbsp;
    {% if period != 30 %}<a href="{{ modified_url(period='30', page=1) }}">{% endif -%}
        За месяц
    {%- if period != 30 %}</a>{% endif %}
    &nbsp; &nbsp;
    {% if period != 365 %}<a href="{{ modified_url(period='365', page=1) }}">{% endif -%}
        За год
    {%- if period != 365 %}</a>{% endif %}
    &nbsp; &nbsp;
    {% if period != 0 %}<a href="{{ modified_url(period=None, page=1) }}">{% endif -%}
        За всё время
    {%- if period != 0 %}</a>{% endif %}
    &nbsp; &nbsp;
</div>
{% endblock %}

{% block after_list %}
    {% if stories %}{{ paginator(page_obj) }}{% endif %}
{% endblock %}