mini_fiction/views/author.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from datetime import datetime

from flask import Blueprint, current_app, request, render_template, abort, redirect, url_for, jsonify
import flask_babel
from flask_babel import gettext
from flask_login import current_user, login_required, logout_user
from pony.orm import db_session, desc

from mini_fiction.bl.migration import enrich_stories
from mini_fiction.models import Author, Story, StoryComment, Contact, ChangeEmailProfile
from mini_fiction.utils.misc import Paginator
from mini_fiction.utils.views import cached_lists
from mini_fiction.forms.author import AuthorEditEmailForm, AuthorEditPasswordForm
from mini_fiction.forms.author import AuthorEditProfileForm, AuthorEditPrefsForm, AuthorEditSubscriptionsForm
from mini_fiction.validation import ValidationError

bp = Blueprint('author', __name__)


def _get_user_for_edit(user_id=None, select_for_update=False):
    if user_id is None and current_user.id is not None:
        user_id = current_user.id
    if user_id is None:
        abort(404)

    try:
        user_id = int(user_id)
    except ValueError:
        abort(404)

    if user_id != current_user.id and not current_user.is_superuser:
        abort(403)

    try:
        if select_for_update:
            user = Author.get_for_update(id=user_id)
        else:
            user = Author.get(id=user_id)
    except ValueError:  # int out of range
        user = None

    if user is None:
        abort(404)
    return user



@bp.route('/profile/', defaults={'user_id': None, 'comments_page': 1})
@bp.route('/profile/comments/page/<int:comments_page>/', defaults={'user_id': None})
@bp.route('/<user_id>/', defaults={'comments_page': 1})
@bp.route('/<user_id>/comments/page/<int:comments_page>/')
@db_session
def info(user_id=None, comments_page=1):
    if user_id is not None:
        try:
            user_id = int(user_id)
        except ValueError:
            abort(404)

    data = {}

    if user_id is None:
        if not current_user.is_authenticated:
            abort(403)
        author = current_user
        comments_list = StoryComment.bl.select_by_story_author(author)
        comments_list = comments_list.sort_by(desc(StoryComment.id))
        stories = list(author.stories)
        stories.sort(key=lambda x: x.first_published_at or x.date, reverse=True)
        contributing_stories = list(author.contributing_stories)
        contributing_stories.sort(key=lambda x: x.first_published_at or x.date, reverse=True)

        data['all_views'] = Story.bl.get_all_views_for_author(author)

        data['page_title'] = gettext('My cabinet')
        template = 'author_dashboard.html'
    else:
        author = Author.get(id=user_id)
        if not author:
            abort(404)
        author_id = author.id  # обход утечки памяти
        comments_list = StoryComment.select(lambda x: x.author.id == author_id and not x.deleted and x.story_published)
        comments_list = comments_list.sort_by(desc(StoryComment.id))
        data['page_title'] = gettext('Author: {author}').format(author=author.username)
        stories = list(Story.bl.select_by_author(author, for_user=current_user))
        stories.sort(key=lambda x: x.first_published_at or x.date, reverse=True)
        contributing_stories = None
        template = 'author_overview.html'

    comments_count = comments_list.count()
    series = list(author.series)
    paged = Paginator(
        number=comments_page,
        total=comments_count,
        per_page=current_app.config['COMMENTS_COUNT']['author_page'],
        page_arg_name='comments_page',
    )  # TODO: restore orphans?
    comments = paged.slice(comments_list)
    if not comments and comments_page != 1:
        abort(404)

    enrich_stories(stories + (contributing_stories or []))

    data.update({
        'author': author,
        'is_system_user': author.id == current_app.config['SYSTEM_USER_ID'],
        'sub': author.bl.get_stories_subscription(current_user),
        'stories': stories,
        'contributing_stories': contributing_stories,
        'series': series,
        'comments': comments,
        'comments_count': comments_count,
        'comments_short': True,
        'page_obj': paged,
    })

    story_ids = set(x.id for x in stories)
    if contributing_stories:
        story_ids |= set(x.id for x in contributing_stories)
    story_ids |= set(x.story.id for x in comments)

    data.update(cached_lists(story_ids, chapter_view_dates=current_user.detail_view))

    return render_template(template, **data)


@bp.route('/profile/edit/', defaults={'user_id': None}, methods=('GET', 'POST'))
@bp.route('/<user_id>/edit/', methods=('GET', 'POST'))
@db_session
@login_required
def edit_general(user_id=None):
    user = _get_user_for_edit(user_id, select_for_update=request.method == 'POST')

    contacts = list(Contact.select(lambda x: x.author == user).order_by(Contact.id))

    form = AuthorEditProfileForm(data={
        'bio': user.bio,
        'contacts': [
            {'name': c.name, 'value': c.value}
            for c in contacts
        ] + [{'name': '', 'value': ''}]
    })

    if user.image is None:
        del form.delete_avatar

    ctx = {
        'page_title': 'Основные настройки',
        'settings_tab': 'general',
        'user': user,
        'user_is_current': user.id == current_user.id,
        'form': form,
        'non_field_errors': [],
        'saved': False,
    }

    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user.bl.update(
                    form.data,
                    modified_by_user=current_user,
                    fill_admin_log=user.id != current_user.id,
                )
            except ValidationError as exc:
                form.set_errors(exc.errors)
            else:
                ctx['saved'] = True

    return render_template('profile_edit_general.html', **ctx)


@bp.route('/profile/edit/mail/', defaults={'user_id': None}, methods=('GET', 'POST'))
@bp.route('/<user_id>/edit/mail/', methods=('GET', 'POST'))
@db_session
@login_required
def edit_mail(user_id=None):
    user = _get_user_for_edit(user_id, select_for_update=request.method == 'POST')

    cep = ChangeEmailProfile.get(user=user)
    new_email = cep.email if cep else None

    form = AuthorEditEmailForm(data={'email': new_email or user.email})
    non_field_errors = []

    ctx = {
        'page_title': 'Настройки почты',
        'settings_tab': 'mail',
        'user': user,
        'user_is_current': user.id == current_user.id,
        'form': form,
        'non_field_errors': non_field_errors,
        'new_email': new_email,
        'email_changed': False,
        'saved': False,
    }

    if request.method == 'POST':
        if form.validate_on_submit():
            if not user.bl.check_password(form.password.data):
                non_field_errors.append(gettext('Password is incorrect'))
            else:
                try:
                    ctx['email_changed'] = user.bl.update_email_with_confirmation(form.email.data)
                    ctx['new_email'] = form.email.data if ctx['email_changed'] else None
                    ctx['saved'] = True
                except ValidationError as exc:
                    form.set_errors(exc.errors)

    return render_template('profile_edit_mail.html', **ctx)


@bp.route('/profile/edit/security/', defaults={'user_id': None}, methods=('GET', 'POST'))
@bp.route('/<user_id>/edit/security/', methods=('GET', 'POST'))
@db_session
@login_required
def edit_security(user_id=None):
    user = _get_user_for_edit(user_id, select_for_update=request.method == 'POST')

    password_form = AuthorEditPasswordForm()
    password_form_errors = []

    ctx = {
        'page_title': 'Настройки безопасности',
        'settings_tab': 'security',
        'user': user,
        'user_is_current': user.id == current_user.id,
        'password_form': password_form,
        'password_form_errors': password_form_errors,
    }

    if request.method == 'POST':
        if password_form.validate_on_submit():
            if not user.bl.check_password(password_form.old_password.data):
                password_form_errors.append(gettext('Old password is incorrect'))
            elif not user.bl.is_password_good(password_form.new_password_1.data):
                password_form_errors.append(gettext('Password is too bad, please change it'))
            else:
                user.bl.set_password(password_form.new_password_1.data)
                logout_user()
                user.bl.reset_session_token()
                return redirect(url_for('auth.login'))

    return render_template('profile_edit_security.html', **ctx)


@bp.route('/profile/edit/personal/', defaults={'user_id': None}, methods=('GET', 'POST'))
@bp.route('/<user_id>/edit/personal/', methods=('GET', 'POST'))
@db_session
@login_required
def edit_personal(user_id=None):
    user = _get_user_for_edit(user_id, select_for_update=request.method == 'POST')


    form = AuthorEditPrefsForm(data={
        # 'excluded_categories': user.excluded_categories_list,
        'timezone': user.timezone or current_app.config['BABEL_DEFAULT_TIMEZONE'],
        'detail_view': user.detail_view,
        'nsfw': user.nsfw,
        'comments_per_page': (
            user.comments_per_page
            if user.comments_per_page is not None
            else current_app.config['COMMENTS_COUNT']['page']
        ),
        'comments_maxdepth': (
            user.comments_maxdepth
            if user.comments_maxdepth is not None
            else current_app.config['COMMENTS_TREE_MAXDEPTH']
        ),
        'comment_spoiler_threshold': (
            user.comment_spoiler_threshold
            if user.comment_spoiler_threshold is not None
            else current_app.config['COMMENT_SPOILER_THRESHOLD']
        ),
        'header_mode': {'': 2, 'off': 0, 'l': 1, 'ls': 2}[user.header_mode],

mini_fiction/views/news.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from flask import Blueprint, current_app, render_template, abort, request, jsonify, redirect, url_for
from flask_babel import gettext
from flask_login import current_user, login_required
from markupsafe import Markup
from pony.orm import db_session, desc

from mini_fiction.models import NewsItem
from mini_fiction.forms.comment import CommentForm
from mini_fiction.utils.views import paginate_view
from mini_fiction.utils.misc import calc_maxdepth

bp = Blueprint('news', __name__)


@bp.route('/page/last/', defaults={'page': -1})
@bp.route('/', defaults={'page': 1})
@bp.route('/page/<int:page>/')
@db_session
def index(page):
    objects = NewsItem.select().sort_by(desc(NewsItem.id))

    return paginate_view(
        'news/index.html',
        objects,
        count=objects.count(),
        page_title=gettext('News'),
        objlistname='news',
        per_page=100,
    )


@bp.route('/<name>/', defaults={'comments_page': -1})
@bp.route('/<name>/comments/page/<int:comments_page>/')
@db_session
def show(name, comments_page):
    newsitem = NewsItem.get(name=name)
    if not newsitem:
        abort(404)

    if newsitem.is_template:
        template = current_app.jinja_env.from_string(newsitem.content)
        template.name = 'db/news/{}.html'.format(name)
        content = render_template(template, newsitem_name=newsitem.name, newsitem_title=newsitem.title)
    else:
        content = newsitem.content

    per_page = current_user.comments_per_page or current_app.config['COMMENTS_COUNT']['page']
    maxdepth = None if request.args.get('fulltree') == '1' else calc_maxdepth(current_user)

    comments_count, paged, comments_tree_list = newsitem.bl.paginate_comments(comments_page, per_page, maxdepth)
    paged.page_arg_name = 'comments_page'
    if not comments_tree_list and paged.number != 1:
        abort(404)

    comment_ids = [x[0].id for x in comments_tree_list]
    if current_user.is_authenticated:
        comment_votes_cache = newsitem.bl.select_comment_votes(current_user, comment_ids)
    else:
        comment_votes_cache = {i: 0 for i in comment_ids}

    data = {
        'page_title': newsitem.title,
        'newsitem': newsitem,
        'content': Markup(content),
        'comments_count': comments_count,
        'page_obj': paged,
        'comments_tree_list': comments_tree_list,
        'comment_form': CommentForm(),
        'comment_votes_cache': comment_votes_cache,
        'sub_comments': newsitem.bl.get_comments_subscription(current_user),
    }

    return render_template('news/show.html', **data)


@bp.route('/<name>/comments/subscribe/', methods=('POST',))
@db_session
@login_required
def comments_subscribe(name):
    newsitem = NewsItem.get(name=name)
    if not newsitem:
        abort(404)

    newsitem.bl.subscribe_to_comments(
        current_user,
        email=request.form.get('email') == '1',
        tracker=request.form.get('tracker') == '1',
    )

    if request.form.get('short') == '1':
        return jsonify(success=True)
    return redirect(url_for('newsitem.show', name=newsitem.name))

mini_fiction/views/tags.py
import json

from flask import Blueprint, current_app, request, render_template, abort, redirect, url_for
from flask_login import current_user
from pony.orm import db_session, desc

from mini_fiction.bl.migration import enrich_stories
from mini_fiction.logic import tags
from mini_fiction.models import Story, Tag, StoryContributor, StoryTag
from mini_fiction.utils.views import cached_lists
from mini_fiction.utils.misc import Paginator

bp = Blueprint('tags', __name__)


@bp.route('/tags/')
@db_session
def index():
    sort_raw = request.args.get('sort')
    sort = sort_raw in tags.TAG_SORTING and sort_raw or 'name'
    categories = tags.get_tags_with_categories(sort=sort)
    return render_template('tags/index.html', page_title='Теги', categories=categories, sort=sort)


@bp.route('/tag/<tag_name>/page/last/', defaults={'page': -1})
@bp.route('/tag/<tag_name>/', defaults={'page': 1})
@bp.route('/tag/<tag_name>/page/<int:page>/')
@db_session
def tag_index(tag_name, page):
    iname = tags.normalize_tag(tag_name)
    if not iname:
        abort(404)
    tag = Tag.get(iname=iname)
    if tag and tag.is_alias_for is not None:
        if tag.is_alias_for.is_alias_for:
            raise RuntimeError('Tag alias {} refers to another alias {}!'.format(tag.id, tag.is_alias_for.id))
        tag = tag.is_alias_for
    if not tag or tag.is_blacklisted:
        abort(404)
    if tag.iname != tag_name:
        return redirect(url_for('tags.tag_index', tag_name=tag.iname, page=page))

    objects = Story.bl.select_by_tag(tag, user=current_user)
    objects = objects.prefetch(Story.characters, Story.contributors, StoryContributor.user, Story.tags, StoryTag.tag, Tag.category)
    objects = objects.sort_by(desc(Story.first_published_at), desc(Story.id))

    page_obj = Paginator(page, objects.count(), per_page=current_app.config['STORIES_COUNT']['tags'])
    objects = page_obj.slice_or_404(objects)

    enrich_stories(objects)

    return render_template(
        'tags/tag_index.html',
        page_title=tag.name,
        tag=tag,
        aliases=[x.name for x in tags.get_aliases_for([tag])[tag.id]],
        category=tag.category,
        stories=objects,
        page_obj=page_obj,
        **cached_lists([x.id for x in objects], chapter_view_dates=current_user.detail_view)
    )


@bp.route('/tags/autocomplete.json')
@db_session
def autocomplete():
    tag_name = (request.args.get('tag') or '').strip()

    result_tags = []
    is_default = False
    data = None

    if len(tag_name) < 2:
        # Предложения по умолчанию, чтобы пусто не было (кэшируются)
        is_default = True
        data = current_app.cache.get('tags_autocomplete_default')
        if not data:
            # Отдаём все теги, отсортированные по популярности
            result_tags = tags.get_all_tags(sort="stories")

    else:
        result_tags = tags.search_by_prefix(tag_name)

    if not data:
        data = build_tags_autocomplete_json(result_tags)
        data['success'] = True
        data = json.dumps(data, ensure_ascii=False, sort_keys=True)
        if is_default:
            current_app.cache.set('tags_autocomplete_default', data, timeout=600)

    response = current_app.response_class(data, mimetype='application/json')
    response.headers['X-Robots-Tag'] = 'noindex'
    return response


def build_tags_autocomplete_json(tags_for_autocomplete):
    aliases = tags.get_aliases_for(tags_for_autocomplete, hidden=True)

    return {
        'tags': [
            {
                'id': tag.id,
                'name': tag.name,
                'url': url_for('tags.tag_index', tag_name=tag.iname),
                'is_spoiler': tag.is_spoiler,
                'description': tag.description,
                'stories_count': tag.published_stories_count,
                'aliases': [x.iname for x in aliases[tag.id]],
                'category_id': tag.category.id if tag.category else 0,
            }
            for tag
            in tags_for_autocomplete
        ],
    }

mini_fiction/templates/includes/abuse_report_content.html
{% from 'macro.html' import comment_html with context %}

{%- if abuse -%}
    {% if abuse.resolved_at %}
        {% if abuse.accepted %}Жалоба была принята.{% else %}Жалоба была отклонена.{% endif %}

    {% elif abuse.user.id == current_user.id %}
        Вы уже подавали жалобу на этот объект, указав следующую причину:
        <blockquote>{{ abuse.reason }}</blockquote>
    {% else %}
        ?
    {% endif %}
{%- endif -%}

{%- if can_abuse -%}
<input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
<input type="hidden" name="next" value="{{ next }}" />

{% if target_type == 'story' %}
    Вы собираетесь пожаловаться на рассказ <a href="{{ url_for('story.view', pk=target.id) }}"><b>{{ target.title }}</b></a>.<br/>
{% elif target_type == 'storycomment' %}
    Вы собираетесь пожаловаться на комментарий к рассказу <a href="{{ url_for('story.view', pk=target.story.id) }}"><b>{{ target.story.title }}</b></a>:
    <div class="comment-item" id="{{ target.local_id }}">
        {{ comment_html(target, with_controls=False, with_vote=False) }}
    </div>
{% elif target_type == 'newscomment' %}
    Вы собираетесь пожаловаться на комментарий к новости <a href="{{ url_for('news.show', name=target.newsitem.name) }}"><b>{{ target.newsitem.title }}</b></a>:
    <div class="comment-item" id="{{ target.local_id }}">
        {{ comment_html(target, with_controls=False, with_vote=False) }}
    </div>
{% endif %}

Укажите причину жалобы:<br/>
<div class="control-group{% if errors %} error{% endif %}">
{% if errors %}
    <div class="help-block">{% for error in errors %}
        {{ error }}
        {%- if not loop.last %}<br/>{% endif %}
    {% endfor %}</div>
{% endif %}
<textarea style="width: 100%; height: 6em; box-sizing: border-box;" name="reason" required placeholder="Спам, оскорбление, чрезмерное количество мата и т. д." autocomplete="off">{{ reason }}</textarea>
</div>
{%- endif -%}

mini_fiction/templates/includes/chapters_short.html
{% for chapter in chapters %}
    {% set authors = chapter.story.authors -%}
    <div class="story-item">
        <h3><a href="{{ url_for('chapter.view', story_id=chapter.story.id, chapter_order=chapter.order) }}">{{ chapter.autotitle }}</a></h3>
          <p><a href="{{ url_for('story.view', pk=chapter.story.id) }}">{{ chapter.story.title }}</a>
          {%- if chapter.story.id in unread_chapters_count and unread_chapters_count[chapter.story.id] > 0 %} (<span class="green" title="{{ _('Unread chapters count') }}">+
            {{- unread_chapters_count[chapter.story.id] -}}
          </span>){% endif %}{% if authors %} {{ pgettext('story_by', 'by') }} <a class="authorlink" href="{{ url_for('author.info', user_id=chapter.story.authors[0].id) }}">{{ authors[0].username }}</a>{% endif %}
          {%- if chapter.first_published_at %} <time datetime="{{ chapter.first_published_at.strftime('%Y-%m-%dT%H:%M:%SZ') }}" title="{{ chapter.first_published_at|datetimeformat(DEFAULT_DATETIME_FORMAT) }}">{{ chapter.first_published_at|timesince }}</time>
          {%- endif -%}
          </p>
    </div>
{% endfor %}

mini_fiction/templates/includes/comments_pagination_story_local.html
{% if page_obj.num_pages != 1 -%}
    {% for page_id in page_obj.iter_pages() %}
        <a
            href="{{ url_for('story_local_comment.view', story_id=local.story.id, comments_page=page_id) }}"
            data-ajax-href="{{ url_for('story_local_comment.ajax', story_id=local.story.id, page=page_id) }}"
            class="js-comment-pagination-btn btn{% if page_id == page_obj.number %} btn-primary{% endif %}">
            {{- page_id -}}
        </a>
    {% endfor %}
{%- endif %}

mini_fiction/templates/includes/notifications.html
{%- import 'includes/notification_comment.html' as nc with context -%}

{% if not notifications -%}
    <h3>{{ _('There is nothing here yet') }}</h3>
{%- endif -%}

{% for item in notifications -%}
{%- if item.show_viewed_line -%}
<div class="notification-viewed-line"><div>{{ _('Viewed notifications') }}</div></div>
{%- endif -%}

<div class="notification" data-type="{{ item.type }}" id="notification{{ item.id }}">
{% if item.broken %}
    <em>Удалено</em>
    {% if item.created_at %}
    <div class="notification-meta">
        <time class="notification-time" datetime="{{ item.created_at.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
            {{ item.created_at|datetimeformat(DEFAULT_DATETIME_FORMAT) }}
        </time>
    </div>
    {% endif %}

{%- elif item.type == 'story_publish' or item.type == 'story_draft' %}
    {% if item.user.is_staff %}
        {{- pgettext('notify_story_publish_draft', 'Moderator') -}}
    {% else %}
        {{- pgettext('notify_story_publish_draft', 'User') -}}
    {% endif %} <a class="authorlink" href="{{ url_for('author.info', user_id=item.user.id) }}">{{ item.user.username -}}
    </a>

    {% if item.type == 'story_publish' -%}
        одобрил рассказ
    {%- else -%}
        отправил в черновики рассказ
    {%- endif %}

    <a href="{{ url_for('story.view', pk=item.story.id) }}">«{{ item.story.title }}»</a>

    <div class="notification-meta">
        <time class="notification-time" datetime="{{ item.created_at.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
            {{ item.created_at|datetimeformat(DEFAULT_DATETIME_FORMAT) }}
        </time>
    </div>

{%- elif item.type == 'author_story' %}
    Опубликован новый рассказ:<br/>
    <a href="{{ url_for('story.view', pk=item.story.id) }}"><b>{{ item.story.title }}</b></a><br/>
    <p class="notification-story-meta">
        {{ ngettext("%(num)d word", "%(num)d words", item.story.words) }} от {% with story=item.story %}{% include 'includes/story_authors_list.html' %}{% endwith %}
    </p>

    <div class="notification-meta">
        <time class="notification-time" datetime="{{ item.created_at.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
            {{ item.created_at|datetimeformat(DEFAULT_DATETIME_FORMAT) }}
        </time>
    </div>

{%- elif item.type == 'story_chapter' %}
    В рассказе <a href="{{ url_for('story.view', pk=item.story.id) }}">«{{ item.story.title }}»</a>
    опубликована новая глава <a href="{{ url_for('chapter.view', story_id=item.story.id, chapter_order=item.chapter.order) }}">«{{ item.chapter.autotitle }}»</a>

    <div class="notification-meta">
        <time class="notification-time" datetime="{{ item.created_at.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
            {{ item.created_at|datetimeformat(DEFAULT_DATETIME_FORMAT) }}
        </time>
    </div>

{%- elif item.type == 'story_reply' %}
<div class="comment-item comment-item-short">
    {% call nc.notification_comment_html(item.comment) %}
        <span class="comment-story-link">
        в ответ на ваш комментарий к рассказу
        <a href="{{ url_for('story.view', pk=item.story.id) }}"><b>{{ item.story.title }}</b></a>
        </span>
        <a class="comment-answer-link" href="{{ url_for('story_comment.add', story_id=item.story.id, parent=item.comment.local_id) }}">Ответить</a>
    {% endcall %}
</div>

{%- elif item.type == 'story_comment' %}
<div class="comment-item comment-item-short">
    {% call nc.notification_comment_html(item.comment) %}
        <span class="comment-story-link">
        к рассказу
        <a href="{{ url_for('story.view', pk=item.story.id) }}"><b>{{ item.story.title }}</b></a>
        </span>
        <a class="comment-answer-link" href="{{ url_for('story_comment.add', story_id=item.story.id, parent=item.comment.local_id) }}">Ответить</a>
    {% endcall %}
</div>

{%- elif item.type == 'story_lreply' %}
<div class="comment-item comment-item-short">
    <div class="comment-item-notify-label">Комментарий от {% if item.extra.is_staff -%}
        модератора
    {%- elif item.extra.is_author -%}
        автора
    {%- elif item.extra.is_editor -%}
        редактора
    {%- else -%}
        бета-читателя
    {%- endif -%}:</div>
    {% call nc.notification_comment_html(item.comment) %}
        <span class="comment-story-link">
        в ответ на ваш комментарий в <a href="{{ url_for('story_local_comment.view', story_id=item.story.id) }}" class="link-inline">редакторской</a> рассказа
        <a href="{{ url_for('story.view', pk=item.story.id) }}"><b>{{ item.story.title }}</b></a>
        </span>
        <a class="comment-answer-link" href="{{ url_for('story_local_comment.add', story_id=item.story.id, parent=item.comment.local_id) }}">Ответить</a>
    {% endcall %}
</div>

{%- elif item.type == 'story_lcomment' %}
<div class="comment-item comment-item-short">
    <div class="comment-item-notify-label">Комментарий от {% if item.extra.is_staff -%}
        модератора
    {%- elif item.extra.is_author -%}
        автора
    {%- elif item.extra.is_editor -%}
        редактора
    {%- else -%}
        бета-читателя
    {%- endif -%}:</div>
    {% call nc.notification_comment_html(item.comment) %}
        <span class="comment-story-link">
        в <a href="{{ url_for('story_local_comment.view', story_id=item.story.id) }}" class="link-inline">редакторской</a> рассказа
        <a href="{{ url_for('story.view', pk=item.story.id) }}"><b>{{ item.story.title }}</b></a>
        </span>
        <a class="comment-answer-link" href="{{ url_for('story_local_comment.add', story_id=item.story.id, parent=item.comment.local_id) }}">Ответить</a>
    {% endcall %}
</div>

{%- elif item.type == 'news_reply' %}
<div class="comment-item comment-item-short">
    {% call nc.notification_comment_html(item.comment) %}
        <span class="comment-newsitem-link">
        в ответ на ваш комментарий к новости
        <a href="{{ url_for('news.show', name=item.newsitem.name) }}"><b>{{ item.newsitem.title }}</b></a>
        </span>
        <a class="comment-answer-link" href="{{ url_for('news_comment.add', news_id=item.newsitem.id, parent=item.comment.local_id) }}">Ответить</a>
    {% endcall %}
</div>

{%- elif item.type == 'news_comment' %}
<div class="comment-item comment-item-short">
    {% call nc.notification_comment_html(item.comment) %}
        <span class="comment-newsitem-link">
        к новости
        <a href="{{ url_for('news.show', name=item.newsitem.name) }}"><b>{{ item.newsitem.title }}</b></a>
        </span>
        <a class="comment-answer-link" href="{{ url_for('news_comment.add', news_id=item.newsitem.id, parent=item.comment.local_id) }}">Ответить</a>
    {% endcall %}
</div>

{%- elif item.type == 'custom' %}
<div class="comment-item comment-item-short">
    <div>{{ item.extra.body|safe }}</div>
    <div class="notification-meta">
        {% if item.user -%}
        <a class="authorlink" href="{{ url_for('author.info', user_id=item.user.id) }}">{{ item.user.username -}}
        </a>
        {%- endif %}
        <time class="notification-time" datetime="{{ item.created_at.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
            {{ item.created_at|datetimeformat(DEFAULT_DATETIME_FORMAT) }}
        </time>
    </div>
</div>

{%- else %}
    {{ item }}
    <div class="notification-meta">
        <time class="notification-time" datetime="{{ item.created_at.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
            {{ item.created_at|datetimeformat(DEFAULT_DATETIME_FORMAT) }}
        </time>
    </div>
{% endif %}
</div>
{%- endfor %}