mini_fiction/views/auth.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from datetime import datetime

from flask import Blueprint, current_app, request, render_template, redirect, url_for, flash
from flask_babel import gettext
from flask_login import login_user, logout_user, current_user
from pony.orm import db_session

from mini_fiction.models import Author
from mini_fiction.captcha import CaptchaError
from mini_fiction.validation import ValidationError
from mini_fiction.forms.login import LoginForm
from mini_fiction.forms.register import AuthorRegistrationForm, AuthorPasswordResetForm, AuthorNewPasswordForm
from mini_fiction.utils.misc import check_own_url


bp = Blueprint('auth', __name__)


@bp.route('/login/', methods=('GET', 'POST'))
@db_session
def login():
    page_title = gettext('Authorization')

    captcha = None
    captcha_error = None

    next_url = check_own_url(
        request.form.get("next") or request.args.get("next") or request.referrer
    ) or url_for("index.index")

    form = LoginForm()
    if form.validate_on_submit():
        data = dict(form.data)
        if current_app.captcha:
            data = current_app.captcha.copy_fields(data, request.form)

        try:
            user = Author.bl.authenticate_by_username(data, request.remote_addr)
            if not login_user(user, remember=True):
                raise ValidationError({'username': [gettext('Cannot login')]})
        except ValidationError as exc:
            form.set_errors(exc.errors)
        except CaptchaError:
            captcha_error = 'Вы не доказали, что вы не робот'
            if not captcha:
                captcha = current_app.captcha.generate()
        else:
            user.last_login = datetime.utcnow()
            user.last_visit = user.last_login
            return redirect(next_url)

    if not captcha and current_app.captcha and Author.bl.need_captcha_for_auth(request.remote_addr):
        captcha = current_app.captcha.generate()

    return render_template(
        'registration/login.html',
        form=form,
        page_title=page_title,
        captcha=captcha,
        captcha_error=captcha_error,
        next_url=next_url,
    )


@bp.route('/register/', methods=('GET', 'POST'))
@db_session
def registration():
    if not current_app.config['REGISTRATION_OPEN']:
        return render_template('registration/registration_closed.html', page_title=gettext('Registration is closed'))

    page_title = gettext('Registration in library')

    captcha = None
    captcha_error = None
    if current_app.captcha:
        captcha = current_app.captcha.generate()

    form = AuthorRegistrationForm()
    if form.validate_on_submit():
        data = dict(form.data)
        if current_app.captcha:
            data = current_app.captcha.copy_fields(data, request.form)
        try:
            Author.bl.register(data)
        except CaptchaError:
            captcha_error = 'Вы не доказали, что вы не робот'
        except ValidationError as exc:
            form.set_errors(exc.errors)
        else:
            if current_app.config['AUTH_LOG']:
                current_app.logger.info('%s requested registration (ID: N/A, IP: %s)', data.get('username'), request.remote_addr)
            return redirect(url_for('auth.registration_complete'))

    return render_template(
        'registration/registration_form.html',
        form=form,
        captcha=captcha,
        captcha_error=captcha_error,
        page_title=page_title,
        username_help=current_app.config['USERNAME_HELP'],
    )


@bp.route('/register/complete/', methods=('GET',))
@db_session
def registration_complete():
    return render_template('registration/registration_complete.html', robots_noindex=True)


@bp.route('/activate/<activation_key>/', methods=('GET',))
@db_session
def registration_activate(activation_key):
    user = Author.bl.activate(activation_key)
    if user:
        if current_app.config['AUTH_LOG']:
            current_app.logger.info('%s registered and activated (ID: %s, IP: %s)', user.username, user.id, request.remote_addr)
        if current_app.config['REGISTRATION_AUTO_LOGIN']:
            login_user(user, remember=True)
        return render_template('registration/activation_complete.html', robots_noindex=True)
    else:
        return render_template('registration/activate.html', robots_noindex=True)


@bp.route('/password/reset/', methods=('GET', 'POST'))
@db_session
def password_reset():
    page_title = 'Восстановление пароля: введите адрес e-mail'

    form = AuthorPasswordResetForm()
    if form.validate_on_submit():
        clean_email = form.email.data.lower().strip()
        users = Author.select(lambda x: x.email.lower() == clean_email)[:2]

        if len(users) == 1:
            users[0].bl.reset_password_by_email()
            return redirect(url_for('auth.password_reset_done'))

        if not users:
            form.set_errors({'email': ['Пользователь с таким e-mail не найден']})
        else:  # len(users) > 1
            form.set_errors({'email': [
                'Как-то получилось, что этот e-mail есть у нескольких пользователей. '
                'Обратитесь к администрации для разбирательств'
            ]})

    return render_template('registration/password_reset_form.html', form=form, page_title=page_title)


@bp.route('/password/reset/done/')
@db_session
def password_reset_done():
    page_title = 'Восстановление пароля: письмо отправлено'
    return render_template('registration/password_reset_done.html', page_title=page_title, robots_noindex=True)


@bp.route('/password/reset/<activation_key>/', methods=('GET', 'POST'))
@db_session
def password_reset_confirm(activation_key):
    page_title = 'Восстановление пароля: новый пароль'
    user = Author.bl.get_by_password_reset_key(activation_key)
    if not user:
        return render_template('registration/password_reset_confirm.html', validlink=False, page_title=page_title)

    form = AuthorNewPasswordForm()
    if form.validate_on_submit():
        if current_app.config['CHECK_PASSWORDS_SECURITY'] and not user.bl.is_password_good(form.new_password1.data):
            flash(gettext('Password is too bad, please change it'))
        else:
            user.bl.set_password(form.new_password1.data)
            if not user.bl.activate_password_reset_key(activation_key):
                raise RuntimeError('activate_password_reset_key returns False')
            return redirect(url_for('auth.password_reset_complete'))
    return render_template('registration/password_reset_confirm.html', validlink=True, form=form, page_title=page_title, robots_noindex=True)


@bp.route('/password/done/')
@db_session
def password_reset_complete():
    page_title = 'Восстановление пароля: пароль восстановлен'
    return render_template('registration/password_reset_complete.html', page_title=page_title, robots_noindex=True)


@bp.route('/changemail/<activation_key>/', methods=('GET',))
@db_session
def new_email_activate(activation_key):
    user = Author.bl.activate_changed_email(activation_key)
    if user:
        if current_app.config['REGISTRATION_AUTO_LOGIN']:
            login_user(user, remember=True)
        return render_template('registration/change_email_complete.html', robots_noindex=True)
    else:
        return render_template('registration/change_email_failed.html', robots_noindex=True)


@bp.route('/logout/', methods=('GET',))
@db_session
def logout():
    if current_app.config['AUTH_LOG'] and current_user.is_authenticated:
        current_app.logger.info('%s logged out (ID: %s, IP: %s)', current_user.username, current_user.id, request.remote_addr)
    logout_user()
    next_url = check_own_url(
        request.args.get("next") or request.referrer
    ) or url_for("index.index")
    return redirect(next_url)

mini_fiction/views/tags.py
import json

from flask import Blueprint, current_app, request, render_template, abort, redirect, url_for
from flask_login import current_user
from pony.orm import db_session, desc

from mini_fiction.bl.migration import enrich_stories
from mini_fiction.logic import tags
from mini_fiction.models import Story, Tag, StoryContributor, StoryTag
from mini_fiction.utils.views import cached_lists
from mini_fiction.utils.misc import Paginator

bp = Blueprint('tags', __name__)


@bp.route('/tags/')
@db_session
def index():
    sort_raw = request.args.get('sort')
    sort = sort_raw in tags.TAG_SORTING and sort_raw or 'name'
    categories = tags.get_tags_with_categories(sort=sort)
    return render_template('tags/index.html', page_title='Теги', categories=categories, sort=sort)


@bp.route('/tag/<tag_name>/page/last/', defaults={'page': -1})
@bp.route('/tag/<tag_name>/', defaults={'page': 1})
@bp.route('/tag/<tag_name>/page/<int:page>/')
@db_session
def tag_index(tag_name, page):
    iname = tags.normalize_tag(tag_name)
    if not iname:
        abort(404)
    tag = Tag.get(iname=iname)
    if tag and tag.is_alias_for is not None:
        if tag.is_alias_for.is_alias_for:
            raise RuntimeError('Tag alias {} refers to another alias {}!'.format(tag.id, tag.is_alias_for.id))
        tag = tag.is_alias_for
    if not tag or tag.is_blacklisted:
        abort(404)
    if tag.iname != tag_name:
        return redirect(url_for('tags.tag_index', tag_name=tag.iname, page=page))

    objects = Story.bl.select_by_tag(tag, user=current_user)
    objects = objects.prefetch(Story.characters, Story.contributors, StoryContributor.user, Story.tags, StoryTag.tag, Tag.category)
    objects = objects.sort_by(desc(Story.first_published_at), desc(Story.id))

    page_obj = Paginator(page, objects.count(), per_page=current_app.config['STORIES_COUNT']['tags'])
    objects = page_obj.slice_or_404(objects)

    enrich_stories(objects)

    return render_template(
        'tags/tag_index.html',
        page_title=tag.name,
        tag=tag,
        aliases=[x.name for x in tags.get_aliases_for([tag])[tag.id]],
        category=tag.category,
        stories=objects,
        page_obj=page_obj,
        **cached_lists([x.id for x in objects], chapter_view_dates=current_user.detail_view)
    )


@bp.route('/tags/autocomplete.json')
@db_session
def autocomplete():
    tag_name = (request.args.get('tag') or '').strip()

    result_tags = []
    is_default = False
    data = None

    if len(tag_name) < 2:
        # Предложения по умолчанию, чтобы пусто не было (кэшируются)
        is_default = True
        data = current_app.cache.get('tags_autocomplete_default')
        if not data:
            # Отдаём все теги, отсортированные по популярности
            result_tags = tags.get_all_tags(sort="stories")

    else:
        result_tags = tags.search_by_prefix(tag_name)

    if not data:
        data = build_tags_autocomplete_json(result_tags)
        data['success'] = True
        data = json.dumps(data, ensure_ascii=False, sort_keys=True)
        if is_default:
            current_app.cache.set('tags_autocomplete_default', data, timeout=600)

    response = current_app.response_class(data, mimetype='application/json')
    response.headers['X-Robots-Tag'] = 'noindex'
    return response


def build_tags_autocomplete_json(tags_for_autocomplete):
    aliases = tags.get_aliases_for(tags_for_autocomplete, hidden=True)

    return {
        'tags': [
            {
                'id': tag.id,
                'name': tag.name,
                'url': url_for('tags.tag_index', tag_name=tag.iname),
                'is_spoiler': tag.is_spoiler,
                'description': tag.description,
                'stories_count': tag.published_stories_count,
                'aliases': [x.iname for x in aliases[tag.id]],
                'category_id': tag.category.id if tag.category else 0,
            }
            for tag
            in tags_for_autocomplete
        ],
    }

mini_fiction/templates/experimental/includes/header.html
{%- from 'experimental/macro.html' import nav_item, user_avatar -%}
{%- set next_url = (url_for(request.endpoint, **request.view_args) if request.endpoint and not request.endpoint.startswith('auth.') and request.view_args != None else None) -%}

<div class="navigation roof">
    <nav aria-label='External links'>
        {{ html_block('experimental_header') }}
    </nav>
    <nav aria-label='User link'>
        <ul class="dropdown__trigger">
            {%- if current_user.is_authenticated %}
                <li><span>{{ current_user.username }}</span></li>
                <li class="dropdown">
                    <div aria-expanded="false"
                         aria-controls="profile-dropdown">
                        {{- user_avatar(current_user, large=True) }}
                    </div>
                    <ul class="dropdown__menu" id="profile-dropdown">
                        {{ nav_item(
                        _('Favorites'),
                        url_for('object_lists.favorites', user_id=current_user.id),
                        matched=is_current_endpoint('object_lists.favorites', user_id=current_user.id)
                    ) }}
                        {{ nav_item(_('Read later'), url_for('object_lists.bookmarks'), 'object_lists.bookmarks') }}
                        {{ nav_item(_('Settings'),url_for('author.edit_general'), matched=is_current_endpoint('author.edit_general')) }}
                        {{ nav_item(_('My profile'),url_for('author.info', user_id=current_user.id), matched=is_current_endpoint('author.info', user_id=current_user.id)) }}
                        {{ nav_item(_("Author's cabinet"),url_for('author.info'), matched=is_current_endpoint('author.info', user_id=None)) }}
                        {% if current_user.is_staff %}
                            {{ nav_item(_('Administration'),url_for('admin_index.index'),'admin_index.index') }}
                        {% endif %}
                        {{ nav_item(_('Log out'), url_for('auth.logout', next=next_url), noajax=True) }}
                    </ul>
                </li>
            {%- else -%}
                {{ nav_item(_('Log in'), url_for('auth.login', next=next_url), 'auth.login') }}
                {%- if config.REGISTRATION_OPEN %}
                    {{ nav_item(_('Register'), url_for('auth.registration'), 'auth.registration') }}
                {% endif %}
            {%- endif -%}
        </ul>
    </nav>
</div>
{%- if current_user.header_mode != 'off' -%}
    {%- set logo = get_current_logopic() -%}
    {%- set logo_label = logo.original_link_label.get(g.locale.language) or logo.original_link_label.get('', '') -%}
    {% if logo -%}
        <div class="logopic" style="background-image: url('{{  url_for('media', filename=logo.bundle.x1194.webp) }}')">
            {% if logo.original_link and logo.original_link_label -%}
                <a rel="noopener noreferrer" href="{{ logo.original_link }}" class="logopic__link" target="_blank">{{ logo_label }}</a>
            {%- endif %}
            {%- if current_user.header_mode == '' or current_user.header_mode == 'ls' -%}
                <div data-bazooka="StoriesCarousel" id="slides">
                    {{ experimental_random_stories() }}
                </div>
            {%- endif %}
        </div>
    {% endif -%}
{%- endif -%}

<div class="navigation plain">
    {% include 'experimental/includes/nav.html' %}
</div>

{# FIXME #}
{#{% include 'includes/important_notifications.html' %}#}

mini_fiction/templates/experimental/includes/nav.html
{%- from 'experimental/macro.html' import nav_item -%}

<nav aria-label='Primary links'>
    <ul>
        {{ nav_item(pgettext('best_stories', 'Best'), url_for('object_lists.top', period='7'), match_endpoint='object_lists.top') }}
        {{ nav_item(gettext('Tags'), url_for('tags.index'), match_endpoint='tags.index') }}
        {{ nav_item(_('Search'), url_for('search.main'), 'search.') }}

        {% if current_user.is_staff -%}
            {{ nav_item('Новые ({})'.format(submitted_stories_count()), url_for('object_lists.submitted'), match_endpoint='object_lists.submitted') }}
            {{ nav_item(gettext('Moderation log'), url_for('editlog.index', all='1', staff='1'), match_endpoint='editlog.index') }}
            {% with abuse_count=unread_abuse_reports_count() %}{% if abuse_count > 0 %}
                {{ nav_item('Жалобы ({})'.format(abuse_count), url_for('admin_abuse_reports.index'), match_endpoint='admin_abuse_reports.') }}
            {% endif %}{% endwith %}
        {% elif current_user.is_authenticated -%}
            {{ nav_item(gettext('Edit log'), url_for('editlog.index'), match_endpoint='editlog.index') }}{% endif -%}
        {{ hook('nav') }}
    </ul>
</nav>
{%- if current_user.is_authenticated %}
    <nav aria-label='Personal links'>
        <ul>
            <li>
                <a href="{{ url_for('story.add') }}" class="{% if is_current_endpoint('story.add') %} active{% endif %}"
                   title="{{ _('Add story') }}">
                    <i class="fas fa-plus fa-lg"></i>
                </a>
            </li>
            {% set notifications_count = get_unread_notifications_count() %}
            <li>
                {# TODO: Add real bell widget #}
                <a href="{{ url_for('notifications.index') }}">
                    <i class="fas fa-bell fa-lg"
                       {% if notifications_count >0 %}data-count="{{ notifications_count }}"{% endif %}></i>
                </a>
            </li>
        </ul>
    </nav>
{%- endif -%}

mini_fiction/templates/experimental/includes/stories_random.html
{%- from 'experimental/macro.html' import character_picture -%}
{%- from 'experimental/macro.html' import tag_link -%}

{% for random_story in random_stories %}
    <input {% if loop.index == 1 %}checked autofocus{% endif %}
           type="radio" id="slide-trigger-{{ loop.index }}" name="slider">
    <label for="slide-trigger-{{ loop.index }}"></label>
    <div class="slide">
        <h3><a href="{{ url_for('story.view', pk=random_story.id) }}">{{ random_story.title }}</a></h3>
        <p>
            <span class="tags">
                {%- for st in random_story.bl.get_tags_list(sort=True) %}
                    {% if st.tag.is_main_tag %}{{ tag_link(st.tag) -}}{% endif %}
                {% endfor -%}
            </span>
        </p>
        <p>{{ random_story.summary|striptags }}</p>
        <p>
            <span class="characters">
                {%- for character in random_story.characters|sort(attribute='id') -%}
                    <a href="{{ url_for('search.simple', search_type='character', search_id=character.id) }}">{{ character_picture(character) }}</a>
                {%- endfor -%}
            </span>
        </p>
    </div>
{% endfor %}